### ISSUE TITLE
Update ml-matrix 6.0.0

### ISSUE THREAD

**Issue by jefffriesen** [mljs/regression-multivariate-linear#10]
I created a branch of this repo and updated:
ml-matrix to 6.0.0
ml-regression-base: 1.2.1

https://github.com/jefffriesen/regression-multivariate-linear/commit/935457b87a11c77f239669b10dbd316f6da85e25

I'm getting different errors than issue #9 

Using the example from the README:
```
import MLR from 'ml-regression-multivariate-linear'
const x = [[0, 0], [1, 2], [2, 3], [3, 4]]
const y = [[0, 0, 0], [2, 4, 3], [4, 6, 5], [6, 8, 7]]
const mlr = new MLR(x, y)
console.log(mlr.predict([3, 3]))
```
I get this error:
```
util.js:65 Uncaught RangeError: vector size must be the same as the number of rows
    at checkColumnVector (util.js:65)
    at Matrix.addColumn (matrix.js:2171)
    at new MultivariateLinearRegression (index.js:37)
```

I know upgrading between v5 and v6 implies breaking changes - I don't know the internals well enough to migrate this project to matrix 6. 

Thanks

**Comment by targos** [comment]
Hi, `ml-matrix` 6.0.0 introduced a few major changes that required some adaptation.
I did this in https://github.com/mljs/regression-multivariate-linear/commit/49848501f381ad0973f45841eaa433ab63892250. All tests are passing. I will check tomorrow that everything is good and make a release.

**Comment by jefffriesen** [comment]
This works great. Thanks
